name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Dockerfile lint
      run: docker run --rm -i hadolint/hadolint hadolint --ignore DL3018 - < Dockerfile
